#!/bin/bash

set -e

if [[ -n "${GT_DOCS_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Starts mdoc watcher for documentation pages in ./docs
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        ./sbt "mdoc --watch"
    fi
fi
